protocol bgp core_v6 {
    local fd00:218:822:473::1 as LOCAL_AS;
    neighbor fd00:218:822:473:: as LOCAL_AS;
    graceful restart on;

    ipv6 {
        import filter import_own_v6;
        export filter export_core_v6;
        next hop self;
    };
}
