protocol bgp vultr_v6 {
    local 2401:c080:1c02:bc5:5400:6ff:fe9f:8b3e as LOCAL_AS;
    neighbor 2001:19f0:ffff::1 as UPSTREAM_AS;
    multihop 2;
    password "${VULTR_BGP_PASSWORD}";
    graceful restart on;

    ipv6 {
        import filter {
            bgp_path.delete([UPSTREAM_AS]);
            if net != ::/0 && !valid_public_v6() then reject;
            bgp_local_pref = 400;
            accept;
        };
        import limit 500000 action restart;
        export filter export_own_v6;
    };
}
