protocol bgp bgpexchange_tw_v6 from upstream_v6 {
    neighbor 2a0e:8f01:1000:78::1 as 24381;
    source address 2a0e:8f01:1000:78::117;

    ipv6 {
        import filter {
            if !valid_public_v6() then reject;
            bgp_local_pref = 310;
            accept;
        };
        import limit 500000 action restart;
    };
}

template bgp bgpexchange_tw_bilateral_v6 from upstream_v6 {
    source address 2a0e:8f01:1000:78::117;

    ipv6 {
        import filter {
            if !valid_public_v6() then reject;
            bgp_local_pref = 310;
            accept;
        };
        import limit 500000 action restart;
    };
}

protocol bgp bgx_tw_200936_113_v6 from bgpexchange_tw_bilateral_v6 { neighbor 2a0e:8f01:1000:78::113 as 200936; }
protocol bgp bgx_tw_219079_116_v6 from bgpexchange_tw_bilateral_v6 { neighbor 2a0e:8f01:1000:78::116 as 219079; }
protocol bgp bgx_tw_201398_20_1398_v6 from bgpexchange_tw_bilateral_v6 { neighbor 2a0e:8f01:1000:78::20:1398 as 201398; }
protocol bgp bgx_tw_201943_10b_v6 from bgpexchange_tw_bilateral_v6 { neighbor 2a0e:8f01:1000:78::10b as 201943; }
protocol bgp bgx_tw_201943_108_v6 from bgpexchange_tw_bilateral_v6 { neighbor 2a0e:8f01:1000:78::108 as 201943; }
protocol bgp bgx_tw_203686_119_v6 from bgpexchange_tw_bilateral_v6 { neighbor 2a0e:8f01:1000:78::119 as 203686; }
protocol bgp bgx_tw_24322_10c_v6 from bgpexchange_tw_bilateral_v6 { neighbor 2a0e:8f01:1000:78::10c as 24322; }
protocol bgp bgx_tw_24322_103_v6 from bgpexchange_tw_bilateral_v6 { neighbor 2a0e:8f01:1000:78::103 as 24322; }
protocol bgp bgx_tw_24322_10a_v6 from bgpexchange_tw_bilateral_v6 { neighbor 2a0e:8f01:1000:78::10a as 24322; }
protocol bgp bgx_tw_24322_10f_v6 from bgpexchange_tw_bilateral_v6 { neighbor 2a0e:8f01:1000:78::10f as 24322; }
protocol bgp bgx_tw_24322_110_v6 from bgpexchange_tw_bilateral_v6 { neighbor 2a0e:8f01:1000:78::110 as 24322; }
protocol bgp bgx_tw_24322_2_4322_v6 from bgpexchange_tw_bilateral_v6 { neighbor 2a0e:8f01:1000:78::2:4322 as 24322; }
protocol bgp bgx_tw_24322_112_v6 from bgpexchange_tw_bilateral_v6 { neighbor 2a0e:8f01:1000:78::112 as 24322; }
protocol bgp bgx_tw_208690_111_v6 from bgpexchange_tw_bilateral_v6 { neighbor 2a0e:8f01:1000:78::111 as 208690; }
protocol bgp bgx_tw_131630_105_v6 from bgpexchange_tw_bilateral_v6 { neighbor 2a0e:8f01:1000:78::105 as 131630; }
protocol bgp bgx_tw_218904_21_8904_v6 from bgpexchange_tw_bilateral_v6 { neighbor 2a0e:8f01:1000:78::21:8904 as 218904; }
protocol bgp bgx_tw_200078_114_v6 from bgpexchange_tw_bilateral_v6 { neighbor 2a0e:8f01:1000:78::114 as 200078; }
protocol bgp bgx_tw_201423_118_v6 from bgpexchange_tw_bilateral_v6 { neighbor 2a0e:8f01:1000:78::118 as 201423; }
protocol bgp bgx_tw_140682_10e_v6 from bgpexchange_tw_bilateral_v6 { neighbor 2a0e:8f01:1000:78::10e as 140682; }
