protocol bgp gre_gateway_v6 {
    local fd00:218:822:100:: as LOCAL_AS;
    neighbor fd00:218:822:100::1 as LOCAL_AS;
    graceful restart on;

    ipv6 {
        import table on;
        import filter {
            if net ~ LUNALIGHT_PREFIXES then {
                if valid_lunalight_v6() then accept;
                reject;
            }
            if valid_public_v6() then accept;
            reject;
        };
        import limit 500000 action restart;
        export filter export_own_v6;
        next hop self;
    };
}
