protocol bgp vultr_edge_v6 {
    local fd00:218:822:473:: as LOCAL_AS;
    neighbor fd00:218:822:473::1 as LOCAL_AS;
    graceful restart on;

    ipv6 {
        import table on;
        export table on;
        import filter {
            if net != ::/0 && !valid_public_v6() then reject;
            bgp_local_pref = 400;
            accept;
        };
        import limit 500000 action restart;
        export filter export_own_v6;
        next hop self;
    };
}
