protocol bgp vultr_edge_v6 {
    local fd00:218:822:473:: as LOCAL_AS;
    neighbor fd00:218:822:473::1 as LOCAL_AS;
    graceful restart on;

    ipv6 {
        export table on;
        import none;
        export filter export_own_v6;
        next hop self;
    };
}
