template bgp evix_rs_v6 from route_server_v6 {
    source address 2602:fed2:fff:ffff:6::11d;

    ipv6 {
        import filter {
            if !valid_public_v6() then reject;
            bgp_local_pref = 310;
            accept;
        };
        import limit 500000 action restart;
    };
}

protocol bgp evix_fremont_rs_v6 from evix_rs_v6 {
    neighbor 2602:fed2:fff:ffff::1 as 137933;
}

protocol bgp evix_amsterdam_rs_v6 from evix_rs_v6 {
    neighbor 2602:fed2:fff:ffff::253 as 209762;
}
