protocol bgp pb_asn218822_v6_c344_1 from upstream_v6 {
    neighbor 2a01:20e:1000:111::1 as 41051;
    source address 2a01:20e:1000:111::2;

    ipv6 {
        import filter {
            if !valid_public_v6() then reject;
            bgp_local_pref = 200;
            accept;
        };
        import limit 500000 action restart;
    };
}
