protocol bgp hkix_gretap_v6 from upstream_v6 {
    neighbor 2602:f92a:1315:2::1 as 203168;
    source address 2602:f92a:1315:2::b5;

    ipv6 {
        import filter {
            if !valid_public_v6() then reject;
            bgp_local_pref = 310;
            accept;
        };
        import limit 500000 action restart;
    };
}
