protocol bgp jsmsr_rs_v6 from route_server_v6 {
    source address 2602:f919:90f:fffa::2188:22;
    neighbor 2602:f919:90f:fffa::2 as 401009;

    ipv6 {
        import filter {
            if !valid_public_v6() then reject;
            bgp_local_pref = 300;
            accept;
        };
        import limit 500000 action restart;
    };
}
