protocol bgp lunalight_v6 from upstream_v6 {
    neighbor fd00:218:822:2014:23::1 as 201423;
    source address fd00:218:822:2014:23::;
    enforce first as on;

    ipv6 {
        import filter import_lunalight_v6;
        receive limit 10 action disable;
        import limit 2 action disable;
    };
}
