template bgp zxix_rs_v6 from route_server_v6 {
    source address 2406:840:1f:1000::21:8822:1;

    ipv6 {
        import filter {
            if !valid_public_v6() then reject;
            bgp_local_pref = 310;
            accept;
        };
        import limit 500000 action restart;
    };
}

protocol bgp zxix_rs1_v6 from zxix_rs_v6 { neighbor 2406:840:1f:1000::1 as 140961; }
protocol bgp zxix_rs2_v6 from zxix_rs_v6 { neighbor 2406:840:1f:1000::2 as 140961; }
