log stderr all;

include "/etc/bird/local.conf";

define LOCAL_AS = 218822;
define UPSTREAM_AS = 64515;
define OWN_PREFIX = 2a06:9801:ff0::/44;

protocol device {
    scan time 10;
}

protocol direct core_direct_v6 {
    ipv6;
    interface "core";
}

filter import_own_v6 {
    if net = OWN_PREFIX && bgp_path.len = 0 then accept;
    reject;
}

filter export_own_v6 {
    if net = OWN_PREFIX && source = RTS_BGP && proto = "core_v6" && bgp_path.len = 0 then accept;
    reject;
}

protocol kernel kernel_v6 {
    ipv6 {
        import none;
        export filter export_own_v6;
    };
}

include "/run/bird/peers/*.conf";
