[Interface]
Address = fd00:218:822:38::/127
ListenPort = 51830
PrivateKey = ${WG_CORE_PRIVATE_KEY}
Table = off
MTU = 1280

[Peer]
PublicKey = K0yiFjydkPBoSf0l3reSpeeQPOOknnbzHMmB+Vy9QBw=
AllowedIPs = fd00:218:822:38::1/128, 2a06:9801:ff0:100::/64
