[Interface]
Address = fd00:218:822:84::/127
ListenPort = 51831
PrivateKey = ${WG_CORE_PRIVATE_KEY}
Table = off
MTU = 1280

[Peer]
PublicKey = 0IAqwUPXdp2lR1WpqVvtTTNyJxQxRtS23EDUFy9Uszs=
AllowedIPs = fd00:218:822:84::1/128, 2a06:9801:ff0:101::/64
