[Interface]
Address = fd00:218:822:473::1/127
ListenPort = 51820
PrivateKey = ${WG_VULTR_EDGE_PRIVATE_KEY}
Table = off
MTU = 1420

[Peer]
PublicKey = 2vnwktCtudjDjCKzy5svVk929/8cSz5GEGZsGF758x0=
AllowedIPs = fd00:218:822:473::/128, 2a06:9801:ff0::/44
