log stderr all;

include "/etc/bird/local.conf";

define LOCAL_AS = 218822;
define OWN_PREFIX = 2a06:9801:ff0::/44;
include "/etc/bird-policy.conf";

protocol device {
    scan time 10;
}

protocol direct direct_v6 {
    ipv6;
}

filter import_core_v6 {
    if net = OWN_PREFIX && bgp_path.len = 0 then accept;
    reject;
}

filter import_lunalight_v6 {
    if valid_lunalight_v6() then {
        bgp_local_pref = 500;
        accept;
    }
    reject;
}

filter export_core_v6 {
    if source = RTS_BGP && net != OWN_PREFIX then accept;
    reject;
}

filter export_upstream_v6 {
    if net = OWN_PREFIX && source = RTS_BGP && proto = "core_v6" && bgp_path.len = 0 then accept;
    reject;
}

filter export_kernel_v6 {
    if source = RTS_BGP then accept;
    reject;
}

protocol kernel kernel_v6 {
    netlink rx buffer 16777216;
    ipv6 {
        import none;
        export filter export_kernel_v6;
    };
    merge paths off;
}

template bgp upstream_v6 {
    local as LOCAL_AS;
    graceful restart on;

    ipv6 {
        import table on;
        import none;
        export filter export_upstream_v6;
    };
}

include "/run/bird/peers/*.conf";
